import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header/Header";
import { Providers } from "./provider/provider";
import ClientSessionProvider from "@/Components/CommonComponents/ClientSessionProvider/ClientSessionProvider";
import { auth } from "../../../backend/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "HOI E-Commerce",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
